export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAILED = 'USER_AUTHENTICATION_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_CART_REQUEST = 'USER_CART_REQUEST';
export const USER_CART_REMOVE_ITEM = 'USER_CART_REMOVE_ITEM';
export const USER_CART_ADD_ITEM = 'USER_CART_ADD_ITEM';
export const USER_CART_REQUEST_SUCCESS = 'USER_CART_REQUEST_SUCCESS';
export const USER_CART_REQUEST_FAILED = 'USER_CART_REQUEST_FAILED'

export const USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST';
export const USER_ORDERS_ADD = 'USER_ORDERS_ADD';
export const USER_ORDERS_REQUEST_SUCCESS = 'USER_ORDERS_REQUEST_SUCCESS';
export const USER_ORDERS_REQUEST_FAILED = 'USER_ORDERS_REQUEST_FAILED';



